apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-test-secret
spec:
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: test-secret
  data:
  - secretKey: foo
    remoteRef:
      key: campnow/hello
      property: foo